### ISSUE TITLE
Unable to connect to chromedriver

### ISSUE THREAD

**Issue by kyamaguchi** [kyamaguchi/amazon_auth#8]
```
Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/service.rb:130:in `connect_until_stable'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/service.rb:74:in `block in start'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/service.rb:71:in `start'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/chrome/bridge.rb:48:in `initialize'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:61:in `new'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:61:in `for'
  from gems/ruby-2.4.1/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver.rb:88:in `for'
  from gems/ruby-2.4.1/gems/capybara-2.14.0/lib/capybara/selenium/driver.rb:22:in `browser'
  from gems/ruby-2.4.1/gems/capybara-2.14.0/lib/capybara/selenium/driver.rb:62:in `visit'
  from gems/ruby-2.4.1/gems/capybara-2.14.0/lib/capybara/session.rb:269:in `visit'
```

**Comment by kyamaguchi** [comment]
This was fixed by
https://stackoverflow.com/questions/23889587/unable-to-connect-to-chromedriver-http-127-0-0-19515-seleniumwebdriverer

```
$ gem uninstall chromedriver-helper

You have requested to uninstall the gem:
	chromedriver-helper-1.1.0

capybara-ember-inspector-1.6.2 depends on chromedriver-helper (>= 0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Remove executables:
	chromedriver, chromedriver-update

in addition to the gem? [Yn]  Y
Removing chromedriver
Removing chromedriver-update
```
