### ISSUE TITLE
Errors on 'visit' ("Cannot navigate to invalid URL")

### ISSUE THREAD

**Issue by kyamaguchi** [kyamaguchi/amazon_auth#9]
```
Selenium::WebDriver::Error::UnknownError: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.4 x86_64)
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:678:in `raw_execute'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:656:in `execute'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:122:in `get'
  from gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
  from gems/capybara-2.14.0/lib/capybara/selenium/driver.rb:62:in `visit'
  from gems/capybara-2.14.0/lib/capybara/session.rb:269:in `visit'
```

**Comment by kyamaguchi** [comment]
Fixed by https://github.com/kyamaguchi/amazon_auth/pull/10/commits/889f20cafb645663f12439ecba87ba82d583b98d in https://github.com/kyamaguchi/amazon_auth/pull/10
